name: 'Java + Maven configuration'
description: 'Java and Mavn version setup'
inputs:
  java-version:
    description: "the java version"
    default: 8
    required: false
  maven-version:
    description: "the maven version"
    default: "3.8.1"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Maven And Java Version
      uses: s4u/setup-maven-action@v1.2.1
      with:
        java-version: ${{ inputs.java-version }}
        maven-version: ${{ inputs.maven-version }}
