version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '05:00'
  open-pull-requests-limit: 0
  target-branch: "7.67.x-blue"
  commit-message:
    prefix: "[bot][blue]"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
