@Library('jenkins-pipeline-shared-libraries')_

node('submarine-static || kie-rhel7') {
    stage('Build lienzo-core') {
        dir("lienzo-core") {
            script {
                echo "LOG:B2-1"
                githubscm.checkoutIfExists('lienzo-core', "$CHANGE_AUTHOR", "$CHANGE_BRANCH", 'kiegroup', "$CHANGE_TARGET")
                echo "LOG:B2-2"
                maven.runMavenWithSubmarineSettings('clean install', true)
                echo "LOG:B2-3"
            }
        }
    }
    stage('Build lienzo-tests') {
        echo "LOG:B3-1"
        maven.runMavenWithSubmarineSettings('clean install', false)
        echo "LOG:B3-2"
    }
}