name: 'Disk Space'
description: 'Cleans up the disk space and reports about the available disk space'

runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: |
        echo "Available storage:"
        df -h
    # Inspired to maximize-build-space action https://github.com/easimon/maximize-build-space
    - name: Free disk space (remove dotnet, android and haskell)
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
    - name: Disk space report after modification
      shell: bash
      run: |
        echo "Available storage:"
        df -h
