version: "2.1"

dependencies: ./release-project-dependencies.yaml

pre: |
  export MAVEN_COMMAND=mvn -B -e -U clean deploy -Dfull -Drelease -DaltDeploymentRepository=local::default::file://${{ env.WORKSPACE }}/community-deploy-dir -Dmaven.test.redirectTestOutputToFile=true -Dmaven.test.failure.ignore=true -Dgwt.memory.settings="-Xmx10g" -Prun-code-coverage -Dcontainer.profile=wildfly -Dcontainer=wildfly -Dintegration-tests=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
  echo "MAVEN_COMMAND=" ${{ env.MAVEN_COMMAND }}
  java -version
default:
  build-command:
    current: |
      ${{ env.MAVEN_COMMAND }}
      ${{ env.WORKSPACE }}/clean-up.sh `pwd`
build:
  - project: kiegroup/jbpm-work-items
    build-command:
      current: ${{ env.MAVEN_COMMAND }}
  - project: kiegroup/kie-docs
    build-command:
      current: ${{ env.MAVEN_COMMAND }}

