name: 'Surefire Report'
description: 'Generates a test report'

runs:
  using: "composite"
  steps: 
    - name: Check Surefire Report
      if: ${{ always() }}
      uses: ScaCap/action-surefire-report@v1.0.10
      with:
        fail_on_test_failures: true
        fail_if_no_tests: false
        skip_publishing: true             
