name: 'Cache Maven'
description: 'Caches maven .m2 folder'
inputs:
  key-prefix:
    description: "the cache key"
    required: true

runs:
  using: "composite"
  steps: 
    # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path:  ~/.m2
        key: ${{ inputs.key-prefix }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys:  ${{ inputs.key-prefix }}-m2
