name: Branch Compilation from issue 225

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'the java version to compile with'
        required: true
        default: '11'
      maven-version:
        description: 'the maven version to compile with'
        required: true
        default: '3.8.1'
      starting-project:
        description: 'the project to start the job with (it is normally the latest leaf from the tree)'
        required: true
        default: 'Ginxo/droolsjbpm-build-bootstrap'
      additional-flags:
        description: 'the additional-flags input. For example "-b main; --fullProjectDependencyTree"'
        required: false
        default: ''
      logger-level:
        description: 'the logger-level. info by default'
        required: true
        default: 'info'
      maven-goals:
        description: 'the maven goals to be executed'
        required: true
        default: 'clean'

jobs:
  build-chain:
    concurrency:
      group: pull_request-${{ github.head_ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Java ${{ github.event.inputs.java-version }} - Maven ${{ github.event.inputs.maven-version }}
    steps:
      - name: Java and Maven Setup
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/maven@main
        with:
          java-version: ${{ github.event.inputs.java-version }}
          maven-version: ${{ github.event.inputs.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ github.event.inputs.java-version }}-maven${{ github.event.inputs.maven-version }}
      - name: Build Chain
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/build-chain@main
        with:
          definition-file: https://raw.githubusercontent.com/Ginxo/droolsjbpm-build-bootstrap/main/.ci/issue_225-config.yaml
          starting-project: ${{ github.event.inputs.starting-project }}
          annotations-prefix: ${{ runner.os }}-${{ github.event.inputs.java-version }}/${{ github.event.inputs.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          flow-type: branch
          additional-flags: ${{ github.event.inputs.additional-flags }}
          logger-level:  ${{ github.event.inputs.logger-level }}
        env:
          MVN_GOAL: ${{ github.event.inputs.maven-goals }}
