name: Pull Request Backporting

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  compute-targets:
    if: ${{ github.event.pull_request.state == 'closed' && github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    outputs:
      target-branches: ${{ steps.set-targets.outputs.targets }}
    steps:
      - name: Set target branches
        id: set-targets
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/parse-labels@main
  
  backporting:
    if: ${{ github.event.pull_request.state == 'closed' && github.event.pull_request.merged && needs.compute-targets.outputs.target-branches != '[]' }}
    name: "[${{ matrix.target-branch }}] - Backporting"
    runs-on: ubuntu-latest
    needs: compute-targets
    strategy:
      matrix: 
        target-branch: ${{ fromJSON(needs.compute-targets.outputs.target-branches) }}
      fail-fast: true
    steps:
      - name: Backporting
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/backporting@main
        with:
          target-branch: ${{ matrix.target-branch }}
